"""Phase 3: add capability field to provider_configs

Revision ID: 94221c4a56b8
Revises: 10c5db86fecb
Create Date: 2026-08-04 19:09:55.997708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94221c4a56b8'
down_revision = '10c5db86fecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: NOT dropping ix_document_chunks_embedding_hnsw — see the same
    # note in the Phase 3 chat-tables migration; Alembic flags it as
    # "removed" only because it isn't represented in the SQLAlchemy model.
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        # server_default required here since provider_configs already has
        # rows by the time this runs in any real deployment; NOT NULL alone
        # would fail against existing data.
        batch_op.add_column(sa.Column('capability', sa.String(length=20), nullable=False, server_default='llm'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_column('capability')

    # ### end Alembic commands ###
