"""Phase 5: observability_config (LangSmith settings)

Revision ID: da056f8864ea
Revises: 9a99b597a006
Create Date: 2026-08-05 11:51:35.825825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da056f8864ea'
down_revision = '9a99b597a006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observability_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('tracing_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(length=20), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: NOT dropping ix_document_chunks_embedding_hnsw — fifth recurrence
    # of the same documented Alembic false-positive (see Migration History
    # in the README). At this point it's worth genuinely fixing at the
    # source rather than re-noting every phase — see the TODO in the
    # Phase 5 write-up.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observability_config')
    # ### end Alembic commands ###
