"""Phase 5: had_error flag on chat_messages

Revision ID: f2761cda744a
Revises: da056f8864ea
Create Date: 2026-08-05 12:17:37.046400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2761cda744a'
down_revision = 'da056f8864ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        # server_default required: chat_messages already has rows by the
        # time this runs in any real deployment (same class of issue as
        # the Phase 3 capability-column migration).
        batch_op.add_column(sa.Column('had_error', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('had_error')

    # ### end Alembic commands ###
